<?php

namespace msmBundle\Entity;

/**
 * ArchivesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivesRepository extends \Doctrine\ORM\EntityRepository
{
}
