<?php

namespace msmBundle\Entity;

/**
 * seminarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class seminarsRepository extends \Doctrine\ORM\EntityRepository
{
}
