<?php

namespace msmBundle\Entity;

/**
 * sessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sessionsRepository extends \Doctrine\ORM\EntityRepository
{
}
