<?php

namespace Proxies\__CG__\JMS\Payment\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FinancialTransaction extends \JMS\Payment\CoreBundle\Entity\FinancialTransaction implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'credit', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'extendedData', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'extendedDataOriginal', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'id', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'payment', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'processedAmount', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'reasonCode', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'referenceNumber', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'requestedAmount', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'responseCode', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'state', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'createdAt', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'updatedAt', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'trackingId', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'transactionType');
        }

        return array('__isInitialized__', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'credit', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'extendedData', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'extendedDataOriginal', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'id', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'payment', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'processedAmount', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'reasonCode', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'referenceNumber', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'requestedAmount', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'responseCode', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'state', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'createdAt', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'updatedAt', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'trackingId', '' . "\0" . 'JMS\\Payment\\CoreBundle\\Entity\\FinancialTransaction' . "\0" . 'transactionType');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FinancialTransaction $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCredit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredit', array());

        return parent::getCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function getExtendedData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtendedData', array());

        return parent::getExtendedData();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayment', array());

        return parent::getPayment();
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessedAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessedAmount', array());

        return parent::getProcessedAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getReasonCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReasonCode', array());

        return parent::getReasonCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferenceNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferenceNumber', array());

        return parent::getReferenceNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestedAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestedAmount', array());

        return parent::getRequestedAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getResponseCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponseCode', array());

        return parent::getResponseCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingId', array());

        return parent::getTrackingId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionType', array());

        return parent::getTransactionType();
    }

    /**
     * {@inheritDoc}
     */
    public function onPostLoad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPostLoad', array());

        return parent::onPostLoad();
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', array());

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredit(\JMS\Payment\CoreBundle\Model\CreditInterface $credit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredit', array($credit));

        return parent::setCredit($credit);
    }

    /**
     * {@inheritDoc}
     */
    public function setExtendedData(\JMS\Payment\CoreBundle\Model\ExtendedDataInterface $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtendedData', array($data));

        return parent::setExtendedData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setPayment(\JMS\Payment\CoreBundle\Model\PaymentInterface $payment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayment', array($payment));

        return parent::setPayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function setProcessedAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcessedAmount', array($amount));

        return parent::setProcessedAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function setReasonCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReasonCode', array($code));

        return parent::setReasonCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function setReferenceNumber($referenceNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferenceNumber', array($referenceNumber));

        return parent::setReferenceNumber($referenceNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestedAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestedAmount', array($amount));

        return parent::setRequestedAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function setResponseCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponseCode', array($code));

        return parent::setResponseCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackingId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackingId', array($id));

        return parent::setTrackingId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionType', array($type));

        return parent::setTransactionType($type);
    }

}
